POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "username": "banana3" ,
    "password" : "banana123" 
    
}


###
POST http://127.0.0.1:3000/signup 
Content-Type: application/json

{
    "username" : "banana3",
    "password" : "banana123"
}